// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AlertTest3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void alertTest3() {
    driver.get("https://letcode.in/alert");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.id("accept")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hey! Welcome to LetCode"));
    driver.findElement(By.id("confirm")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you happy with LetCode?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.id("prompt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Enter your name"));
    {
      Alert alert = driver.switchTo().alert();
      alert.sendKeys("Harrish")
      alert.accept();
    }
    driver.findElement(By.id("modern")).click();
    driver.findElement(By.cssSelector(".modal-close")).click();




  }
}
